### ISSUE TITLE
[FEATURE REQUEST] Ability to allow specific pages/patterns to not use `window.forTrusted()` so that these pages can trigger vimium key presses

### ISSUE THREAD

**Issue by afilp** [gdh1995/vimium-c-helpers#6] opened 2020-11-18 10:16 UTC
Hi! 

This is a copy from the other repo to discuss it here:
https://github.com/philc/vimium/issues/3710
 
You responded that this can be done with a custom extension, but this causes problems as the extension will be untrusted and will take time to implement as a different extension.

So, I propose, what if we have an option in `vimium-c` like this?
![image](https://user-images.githubusercontent.com/7850073/99516875-5d79dc80-2997-11eb-855c-e23c7162939b.png)

This way we can accomplish the "automatic" load of vomnibar on selected special pages of ours!

I can then have my special page get the focus with `WindowsKey + 1` and therefore achieve immediate access to the vomnibar from anywhere I am in Windows (not just from Chrome!).

Thanks!

------

My question there was:

I actually have a use case where I need to accress the vimium API programmatically.

I want my test page to open automatically, on load and on getting the focus, so that I can immediately search for any open web page in my tabs.

See a test page here, with explanation of the goal:
https://www.likno.com/test/blank/

--------

**Comment by afilp** [comment] 2020-11-22 22:38
Thanks @gdh1995 ! 
The visibility feature is needed in my use case where I want the vomnibar to show automatically when I switch to that particular tab (with the particular web page).

Thanks again!

**Comment by gdh1995** [comment] 2020-12-01 16:23
Hello, now I get a new idea to do what (I think) this issue wants:

I'll add a feature to run any JavaScript code on its inner blank page, and then you can do anything you want, including sending messages to Vimium C.

Will it work for you?

**Comment by afilp** [comment] 2020-12-01 16:43
This seems like a good idea if it is possible!

To be able to trigger vomnibar commands with our own Javascript from within the web page that is loaded!

P.S. Where can we find the vimium Javascript API (or similar) for such commands?

Thanks!

**Comment by snsnsjsn** [comment] 2021-02-13 09:43
我用 listary ，定义一个快捷键g空格+关键字（goolge 搜索）， b空格+关键字（baidu搜索）
![image](https://user-images.githubusercontent.com/11435527/107846949-d667c380-6e22-11eb-8ff4-9cedc7a4103b.png)
![image](https://user-images.githubusercontent.com/11435527/107846955-e089c200-6e22-11eb-9f44-cd9a7da66a21.png)

![image](https://user-images.githubusercontent.com/11435527/107846961-eda6b100-6e22-11eb-8383-d50191bafd9c.png)

这样我就可以在windows桌面全局搜索

**Comment by gdh1995** [comment] 2021-02-14 14:03
@afilp Sorry for no response in recent days.

The idea to run arbitrary user script seems impossible to implement in a further web-extension platform - Chrome is promoting [extension manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/), which has came in Chrome 88, and they said the current `manifest v2` will be disallowed in about 1 year.

Then, I may turn to the old idea of adding a new option to auto load Vomnibar once inited.

**Comment by gdh1995** [comment] 2021-06-25 05:57
Hello Vimium C v1.90.2 has supported this feature: you may add map t createTab $then="Vomnibar.activate" to custom key mappings.

$then can be a mapped key sequence or a command name, and when it's a key sequence like o and g0, createTab will invoke the mapping rule when a new tab gets ready.

If you're using global (browser-level) shortcuts, then shortcut createTab $then="o" should also work.

BTW, #7 seems a duplicate of this issue.

**Closed** 2021-09-06 08:36 UTC
Labels: enhancement
